name: Copilot Request
on:
  issues:
    types: [opened, reopened]

jobs:
  add:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TOKEN }}
      USERS: ${{ github.event.issue.user.login }}
      ORG: ${{ github.repository_owner }}
    steps:
      - name: Run Copilot Request
        continue-on-error: true # temp
        run: |
          gh api \
            --method POST \
            /orgs/$ORG/copilot/billing/selected_users \
            -f "selected_usernames[]=$USERS"
      - name: Add Comment
        run: |
          gh api \
            --method POST \
            /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -f "body=Succesfully added a copilot license for $USERS"
      - name: Close Issue
        run: |
          gh api \
            --method PATCH \
            /repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -f "state=closed"